version: '3'

services:
  hello-guest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BRANCH=hello-world-1
      - PORT=5000
    ports:
      - "5000:5000"

  hello-admin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BRANCH=hello-world-2
      - PORT=5005
    ports:
      - "5005:5005"

  hello-qa:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BRANCH=hello-world-3
      - PORT=5007
    ports:
      - "5007:5007"