version: '3'

services:
  hello-guest:
    build:
      context: ../hello_world_1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  hello-admin:
    build:
      context: ../hello_world_2
      dockerfile: Dockerfile
    ports:
      - "5005:5005"

  hello-qa:
    build:
      context: ../hello_world_3
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
